### PR TITLE
navbar added

### PR DESCRIPTION
**Pull request by indevi**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by indevi** [comment]
Hey @grace-omotoso  Here's the PR for navbar, please lemme know the feedback

**Review by grace-omotoso — COMMENTED** [review]
The footer is a bit too large. Please, check your styling

**Comment by indevi** [comment]
Implemented feedback

**Comment by indevi** [comment]
hey @kpham841 Can you please look into this code and tell me why the `script` tag isnt getting imported into my html file. 
This is necessary for the mobile view 

The problem is to import my navbarJs file into my html file

**Review by grace-omotoso — APPROVED** [review]
I will approve this because of other PRs waiting for this. The effect when we hover on navbar can be better

**Pull request merged**
