### PR TITLE
 ADD Dark-Theme toggle

### PR DESCRIPTION
**Pull request by trinhcaokhoa**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.
- Dark mode :

Screenshot (3)
- Light mode:
Screenshot (4)

### CODE REVIEW

**Comment by trinhcaokhoa** [comment]
@grace-omotoso Can you please review my PR. Thank you

**Comment by kph4m** [comment]
Hey Khoa, maybe make the card background a darker color so the contrast isn't too strong

**Review by grace-omotoso — COMMENTED** [review]
This will be a perfect feature that sits on the navbar @ShivamTyagi12345 @carlykiang how can we have the navbar ready ASAP?

**Comment by indevi** [comment]
> This will be a perfect feature that sits on the navbar @ShivamTyagi12345 @carlykiang how can we have the navbar ready ASAP?

Yes it most definitely will be. We will change the background and have it merged. Just few additions to go

**Pull request closed without merging**
