### PR TITLE
Added the description as per POD details

### PR DESCRIPTION
**Pull request by ConnectBhawna**
## Please, go through these steps before you submit a PR.

- [ ] My Pod Leader knows I'm working on this Pull Request
- [ ] I've explained what the Pull Request is adding.
- [ ] I've explained why this is important.

### CODE REVIEW

**Review by grace-omotoso — COMMENTED** [review]
We have an open PR that does this. Please, sink with Mansi and have one closed

**Comment by pixawna** [comment]
Sure mam, Mansi started working on another issue. She told me to work in this one

**Review by grace-omotoso — COMMENTED** [review]
Needs improvement
- Description paragraph should be justified
- Section headers should
- Add logo on. footer (replace the text byte badger text with logo)

**Comment by pixawna** [comment]
Done mam 
Thanks

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
@Bhawna1203 The byte on the byte badger seems gone, @ShivamTyagi12345 can help if needed.

**Comment by indevi** [comment]
@Bhawna1203 please use this

Logo

**Comment by pixawna** [comment]
Now completely Done Mam

**Comment by grace-omotoso** [comment]
@Bhawna1203 please, fix merge conflicts

**Comment by pixawna** [comment]
Okkk mam, done

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
