### PR TITLE
Issue 10 Added map

### LINKED ISSUE #10: Add a map showing all the countries that fellows are located in
Underneath projects and fellows, have an interactive map that displays where everyone is located.

- [ ] When you click on the pin location for that fellow, it gives you a card with information about the fellow (similar to the fellow section

You can chose to have pins or use circular profile pictures to show where everyone is on the map. You could remove the fellows section and replace it with the map.

### PR DESCRIPTION
**Pull request by norachams**
This PR will close #10  
## Please, go through these steps before you submit a PR.

- [X] My Pod Leader knows I'm working on this Pull Request
- [X] I've explained what the Pull Request is adding.
- [X] I've explained why this is important.
-  This PR is adding a map to the website portfolio and location of the fellows.

Screen Shot 2022-11-10 at 7 28 28 PM

### CODE REVIEW

**Review by grace-omotoso — COMMENTED** [review]
Only showing map. Isn't this the issue you will be needing me to add the Google Map API key to?

**Comment by norachams** [comment]
> https://deploy-preview-31--mlh-prep-22-nov-prep-2-portfolio.netlify.app/

Yes, it is. We are still adding fellow info and making changes which Namita is going to raise a PR for tomorrow. This is just a PR for what we did so far.

**Comment by ShivamTyagi12345** [comment]
Implemented feedback

**Review by grace-omotoso — COMMENTED** [review]
There seems to be an existing PR for this issue. Please sync with @namitaarya  and close one of the PRs/

**Comment by namitaarya** [comment]
> There seems to be an existing PR for this issue. Please sync with @namitaarya and close one of the PRs/

You can ignore this one, and look into the other PR. This would be closed by Nora :)

**Comment by grace-omotoso** [comment]
There is another PR for this

**Comment by grace-omotoso** [comment]
Please, fix merge conflicts

**Pull request closed without merging**
